version: '3.8'

services:
  esg-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=esgdb;Username=postgres;Password=password123
    depends_on:
      - db
    networks:
      - esg-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=esgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esg-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  esg-network:
    driver: bridge