name: CI/CD - ESGInteligentes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build release
        run: dotnet build -c Release --no-restore

      - name: Run tests (simulado)
        run: echo "Nenhum teste xUnit configurado. Simulando sucesso."

  docker-build-and-smoke:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t esginteligentes:ci .

      - name: Run container (smoke test)
        run: |
          docker run -d --name esg_ci -p 8080:8080 esginteligentes:ci
          echo "Aguardando container iniciar..."
          sleep 8
          echo "Testando endpoint /api/energia"
          set -o pipefail && curl -f http://localhost:8080/api/energia || (docker logs esg_ci && exit 1)
          docker stop esg_ci && docker rm esg_ci

      - name: Simulated deploy to staging
        run: echo "Deploy para STAGING concluído (simulado)."

      - name: Simulated deploy to production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy para PRODUÇÃO concluído (simulado)."
